# Generated by Django 4.2.3 on 2023-07-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creature_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600)),
                ('image_url', models.URLField(blank=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_creature', to='Creature_API.creature')),
            ],
        ),
    ]
