# Generated by Django 4.2.3 on 2023-07-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creature_API', '0002_megacreature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='megacreature',
            name='image_url',
        ),
        migrations.AddField(
            model_name='creature',
            name='image',
            field=models.ImageField(default='creature_images/default_image.png', upload_to='creature_images/'),
        ),
        migrations.AddField(
            model_name='megacreature',
            name='image',
            field=models.ImageField(default='creature_images/default_image.png', upload_to='creature_images/'),
        ),
    ]
