# Generated by Django 4.2.3 on 2023-07-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creature_API', '0004_category_alter_creature_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='megacreature',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Creature_API.category'),
        ),
        migrations.AlterField(
            model_name='megacreature',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
