# Generated by Django 4.2.3 on 2023-07-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creature_API', '0005_megacreature_category_alter_megacreature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
